[package]
name = "dcc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { version = "1", default-features = false }
embedded-hal = { version = "0.2.7", features = ["unproven"] }
